version: 2.1
orbs:
  protobuf: izumin5210/protobuf@0.1.0
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - protobuf/install
      - run:
          name: "Install protoc plugin"
          command: |
            curl -L https://github.com/grpc/grpc-web/releases/download/1.0.7/protoc-gen-grpc-web-1.0.7-linux-x86_64 --output protoc-gen-grpc-web
            sudo mv protoc-gen-grpc-web /usr/local/bin/
            chmod +x /usr/local/bin/protoc-gen-grpc-web
      - run:
          name: "Install dependencies"
          command: sudo npm -g i nyc
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run webpack
      - run: npm run build
      - run: nyc npm test

      - run:
          name: Generate Code Coverage
          command: nyc report --reporter=text-lcov > coverage.lcov

      - codecov/upload:
          file: coverage.lcov
